# Generated by Django 3.2.5 on 2021-07-31 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roadtrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('estimated_drive', models.IntegerField()),
                ('estimated_budget', models.IntegerField()),
                ('notes', models.TextField()),
                ('location_1', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=100)),
                ('type_of_place', models.CharField(max_length=250)),
                ('location_2', models.CharField(max_length=250)),
                ('state_2', models.CharField(max_length=100)),
                ('type_of_place_2', models.CharField(max_length=250)),
                ('location_3', models.CharField(max_length=250)),
                ('state_3', models.CharField(max_length=100)),
                ('type_of_place_3', models.CharField(max_length=250)),
                ('total_cost', models.IntegerField()),
                ('total_length_of_trip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodging_name', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=100)),
                ('type_of_place', models.CharField(max_length=250)),
                ('cost', models.IntegerField()),
                ('length_of_stay', models.IntegerField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('vehicle', models.TextField()),
                ('requirements_for_trip', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Roadtripping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadtrip', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roadtripping', to='main_app.roadtrips')),
                ('stays', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roadtripping', to='main_app.stays')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roadtripping', to='main_app.user')),
            ],
        ),
    ]
