# Generated by Django 3.2.5 on 2021-07-31 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadtripping',
            name='stays',
        ),
        migrations.CreateModel(
            name='PlanningLodging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadtrip', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='planningLodging', to='main_app.roadtrips')),
                ('stay', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='planningLodging', to='main_app.stays')),
            ],
        ),
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lodging', to='main_app.stays')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lodging', to='main_app.user')),
            ],
        ),
    ]
